### ISSUE TITLE
Custom field mappings

### ISSUE THREAD

**Issue by crazy-man** [DoubleCheck/log-ship-elastic-postfix#18]
Hello,
Everything works great. I can see documents in es.
The problem is that I can't search for complete emails and message-ids(only parts that are separated by dots, @ and other default delimiters). I made a research, seems like instead of a default dynamic mapping, I need to define custom mapping for these fields:
something like:

```

"analyzer": {
        "email": {
          "tokenizer": "uax_url_email"
}
```

and then: 
```
 "mappings": {
    "emails": {
      "properties": {
        "message-id": {
          "type": "string",
          "analyzer": "email"
        }
      }
    }
  }

```
**The question is:** is there a built-in support of custom mappings in log-ship-elastic-postfix?
Or I should write it by myself somewhere before:
logship.js (line 366)
` p2e.elastic.bulk({ body: esBulk, consistency: 'all' }, function (err, res) {`

Looks like creating custom mappings in bulk query is not supported, indexes should be created before insertion.

Thank you,
Constantine

**Comment by msimerson** [comment]
With elasticsearch, you should be creating index map templates, so that every time a new index is created, it's created with your custom mappings.  What those mappings should be really depends upon your application so there's little point in adding them to this library. 

For Message Id and email addresses, I use a not-analyzed field so I can do fast exact matches. YMMV. When I want to do exact and tokenized searches, I use a map multiple types and then the query can specify field or field.raw, depending on what kind of results I want.

**Comment by crazy-man** [comment]
Index Templates is exactly what I was looking for.
Thank you very much!
